
name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t obeng7677/portfolio .

     
      - name: Push image
        run: |
          |  docker login -u obeng7677 -p ${{secrets.REGISTRY_PASS}}
             docker push obeng7677/portfolio